### ISSUE TITLE
Update d4tools version included in python3.11-venv-d4tools

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/docker-base-images#25]
fyi @Jakob37

To the latest version of d4tools - should be 0.3.10, but I see that [a crate for this version is missing](https://crates.io/crates/d4tools/versions):

<img width="995" alt="image" src="https://github.com/Clinical-Genomics/docker-base-images/assets/28093618/01b117b9-8f15-46af-8589-194deb3c9ba4">

**Comment by Jakob37** [comment]
OK, I see, thank you for the update!

**Comment by northwestwitch** [comment]
Looks like it will not be possible to use crates to install the latest. This means I need to change how the software is installed in the docker image
